workflows:
  android-workflow:
    name: Build Android App Only
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk
      - name: Build App Bundle
        script: flutter build appbundle
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
